### ISSUE TITLE
Example of registering a sort function

### ISSUE THREAD

**Issue by ProjectMoon** [ahmed-shariff/org-roam-ql#12]
Hi, excellent project. Using it to organize a bunch of notes in a "homepage" of the notebook.

I'd like to add a custom sort function, specifically to sort on a specific custom property in the org files. I see that org-roam has a `properties` slot, so this should be possible. But I am not an elisp ninja, so an example of how to make a sort function would be very wonderful to have in the readme.

**Comment by ahmed-shariff** [comment]
Thank you, glad to know you find it useful :)

Something I have in my config is the following:
```emacs-lisp
  (org-roam-ql-register-sort-fn "key-order" (lambda (el1 el2)
                                              (string< (cdr (assoc "KEY_ORDER" (org-roam-node-properties el1)))
                                                       (cdr (assoc "KEY_ORDER" (org-roam-node-properties el2))))))
```
It sorts by the property "KEY_ORDER". I hope this helps. I'll add it to the readme as well.
If you run into any issues let me know here.

Meanwhile, ielm is a good place to play around with elisp, it can be fun :D

**Comment by ProjectMoon** [comment]
That's exactly what I needed, thanks!
