### ISSUE TITLE
Problem using variables in org-roam-ql-nodes-files

### ISSUE THREAD

**Issue by lyndhurst** [ahmed-shariff/org-roam-ql#13]
Hi,

I am sorry if this question is dumb, but I figured the package might still be a bit too niche to get help in some forum, and I have spent so much time on this, I just cannot let it go :)

I am trying  to use `org-roam-ql-nodes-files` in a function but I am not having any luck with variables.

To simplify:

```lisp
;; This works fine:
(delete-dups (org-roam-ql-nodes-files '(tags "Test")))


;; All of the following attempts return nil with a '(wrong-type-argument sqlitep nil)'

(defun my-test (tag)
 (delete-dups (org-roam-ql-nodes-files '(tags tag))))

(defun my-test (tag)
 (delete-dups (org-roam-ql-nodes-files '(tags (format "%s" tag)))))

(defun my-test (tag)
 (delete-dups (org-roam-ql-nodes-files '(tags (quote tag)))))

(defun my-test (tag)
 (delete-dups (org-roam-ql-nodes-files '(tags '(tag)))))

(defun my-test (tag)
 (delete-dups (org-roam-ql-nodes-files '(tags '((format "%s" tag))))))

(my-test "Test")
```

Is there any way to make this work ?

Thanks for your time.

**Comment by ahmed-shariff** [comment]
There is no such thing as a dumb question :)

I'm glad to know you worked that out.
