### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by nicolas-graves** [ahmed-shariff/org-roam-ql#3]
Hi! 

I like the project and think it's very useful for my use case. While experimenting with it, I probably would have some contributions to make in the coming week. However, I don't see the point of contributing to an emacs package which reuses quite some gpl3+ code but sets its license to MIT. 

Would you be willing to relicense your code? Or accept contributions with another license?

**Comment by ahmed-shariff** [comment]
Thank you for the interest, this is the first time I am maintaining any project like this. I'll be honest, I really don't think much about the license beyond the "don't sue me" part, atleast in projects like this one, though I understand the hesitation with the MIT license. I am most likely being oblivious to many things here. I'll relicense the code as soon as I can. I don't see any issue with that.

**Comment by ahmed-shariff** [comment]
Updated the license. This made me spend a bit more time learning about the licences :)
Please reach out if I can assist in any way.

**Comment by nicolas-graves** [comment]
Thanks! 
Not an expert either, my main concern was both for you (you're not supposed to be able to license under MIT code that was copied from GPL3+) and for the future of the project (if a part of the code is ever considered for merging in main emacs in a dozen years, anything other than gpl3+ would make everything horribly complicated, and in terms of emacs community it makes more sense).
