### ISSUE TITLE
org-roam-ql-buffer-dispatch returns "Invalid format character %v"

### ISSUE THREAD

**Issue by raphaelfloresca** [ahmed-shariff/org-roam-ql#4]
Whenever I invoke the org-roam-ql-buffer-dispatch in the org-roam buffer, instead of showing the org-roam-ql-buffer constructed from the backlinks in the org-roam buffer, I receive a message which says "Invalid format character %v".

I have tested this out in Doom Emacs and vanilla Emacs, both show the same message.

Otherwise, I can launch the org-roam-ql buffer by running a query, just not through the org-roam buffer.

If you have any suggestions as to why this may be the case, or what I could do to fix it, that would be great.

I've enjoyed this package so far and I'm keen to get it fully working in my workflow. Keep up the great work!

**Comment by raphaelfloresca** [comment]
An update on this: the org-roam-ql buffer works in the org-roam buffer after downgrading to Emacs 28.2.

I had a look at the org-roam-ql source code to try and diagnose the issue, but could not find a '%v'. Unfortunately my elisp skills are not the best, so I'm not sure where else I could look to help diagnose the issue.

**Comment by ahmed-shariff** [comment]
Thank you very much for pointing that out. I have pushed a fix for this.
