### ISSUE TITLE
Add support for lowercase properties in queries

### ISSUE THREAD

**Issue by Delapouite** [ahmed-shariff/org-roam-ql#5]
Hi

In my Org-Roam notes, I tend to always favor lowercase properties-drawer, to avoid the "screaming at your face" of Org-Mode default.

For example:
```org
:properties:
:id: foo
:country: Brazil
:end:
…
```

But then when I want to queries all nodes who have Brazil as a country, I'm forced to use uppercase `COUNTRY`:

```org
#+begin: org-roam-ql :query (properties "COUNTRY" "Brazil") :columns (title) :no-link true
…
#+end
```

instead of `country`:

```org
#+begin: org-roam-ql :query (properties "country" "Brazil") :columns (title) :no-link true
#+end
```

I would much appreciate if it could it be possible to handle the second case transparently to avoid surprise and inconsistency.

Thanks a lot for this package!

**Comment by ahmed-shariff** [comment]
Thank you for pointing that out. Should be fixed now.
