### ISSUE TITLE
the function `em` is not known to be defined.

### ISSUE THREAD

**Issue by hiecaq** [ahmed-shariff/org-roam-ql#9]
https://github.com/ahmed-shariff/org-roam-ql/blob/9f5f1234a69b1df9d65ab947a003060fb5a28b60/org-roam-ql.el#L1008 

This `em` function doesn't seem to be defined on my site.

My Emacs version:
```
GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)
```

**Comment by ahmed-shariff** [comment]
Thanx for catching this. It's a debug function from my config I had missed to properly cleanup.
